Passengers:
    path:       /passengers
    controller: App\Controller\PassengersController::GetPassengers
    methods:    GET

PostPassengers:
    path:       /postPassengers
    controller: App\Controller\PassengersController::PostPassenger
    methods:    POST

PutPassengers:
    path:       /putPassengers/{id}
    controller: App\Controller\PassengersController::PutPassenger
    methods:    PUT

DeletePassengers:
    path:       /deletePassengers/{id}
    controller: App\Controller\PassengersController::DeletePassenger
    methods:    DELETE

GetTickets:
    path:       /ticket
    controller: App\Controller\TicketsController::GetTickets
    methods:    GET

PutTickets:
    path:       /ticket-passengers/{id}
    controller: App\Controller\TicketsController::PutTicket
    methods:    PUT

GetCities:
    path:       /cities
    controller: App\Controller\CitiesController::GetCities
    methods:    GET

GetCity:
    path:       /city/{id}
    controller: App\Controller\CitiesController::GetCity
    methods:    GET

GetFlights:
    path:       /flights
    controller: App\Controller\FlightsController::GetFlights
    methods:    GET

GetFlight:
    path:       /flight/{id}
    controller: App\Controller\FlightsController::GetFlight
    methods:    GET